CREATE DATABASE IF NOT EXISTS TW_REAL_ESTATE_DB;

USE TW_REAL_ESTATE_DB;

-- DROP TABLE IF EXISTS INTERIOR_WEB_POPULATION_MIGRATION_STAGE;
CREATE TABLE IF NOT EXISTS INTERIOR_WEB_POPULATION_MIGRATION_STAGE(
	EACH_YEAR_MONTH_CITY_DISTRICT_ID INT COMMENT '每一年月查詢的ID編號',
    ROC_YEAR VARCHAR(10) COMMENT '中華民國年',
    ROC_MONTH VARCHAR(10) COMMENT '中華民國月',
    CITY_DISTRICT_NAME VARCHAR(10) COMMENT '對應到INTERIOR_WEB_RE_TRANSACTION_FULL_STAGE的CITY_NAME(縣/市)',
    M_MOVE_IN VARCHAR(10) COMMENT '遷入人數男',
    F_MOVE_IN VARCHAR(10) COMMENT '遷入人數女',
    M_MOVE_OUT VARCHAR(10) COMMENT '遷出人數男',
    F_MOVE_OUT VARCHAR(10) COMMENT '遷出人數女',
    M_NET_MIGRATION VARCHAR(10) COMMENT '淨遷徙人數男',
    F_NET_MIGRATION VARCHAR(10) COMMENT '淨遷徙人數女',
    CREATE_TIME DATETIME(4) COMMENT '資料匯入時間',
    CREATE_BY VARCHAR(50) COMMENT '資料建立者',
    UPDATE_TIME DATETIME(4) COMMENT '資料更新時間', -- 未確定是否需要，但先建立
    UPDATE_BY VARCHAR(50) COMMENT '資料更新者',-- 未確定是否需要，但先建立
    CONSTRAINT PK_INTERIOR_WEB_POPULATION_MIGRATION_STORAGE PRIMARY KEY (EACH_YEAR_MONTH_CITY_DISTRICT_ID, ROC_YEAR, ROC_MONTH, CITY_DISTRICT_NAME)
);
