-- 2025-07-04 CREATE DB TW_REAL_ESTATE_DB
CREATE DATABASE IF NOT EXISTS TW_REAL_ESTATE_DB;

USE TW_REAL_ESTATE_DB;

-- INTERIOR = 內政部, WEB = 網站, RE = 不動產, TRANSACTION = 買賣查詢, FULL = FULL STORAGE, FOR ALL RAW DATA
-- 2025-07-13 INTERIOR_WEB_RE_TRANSACTION_FULL_STAGE
-- DROP TABLE IF EXISTS INTERIOR_WEB_RE_TRANSACTION_FULL_STAGE; 
CREATE TABLE IF NOT EXISTS INTERIOR_WEB_RE_TRANSACTION_FULL_STAGE(
	CITY_DISTRICT_ID INT COMMENT '筆數編號',
    BATCH_ID INT COMMENT '批次編號',
    PAGE INT COMMENT '頁數號碼',
    CITY_NAME VARCHAR(100) COMMENT '縣市',
    DISTRICT_NAME VARCHAR(100) COMMENT '鄉鎮區',
    ADDRESS VARCHAR(100) COMMENT '地址',
    COMMUNITY VARCHAR(500) COMMENT '社區名稱',
    TOTAL_PRICE_10K VARCHAR(500) COMMENT '總價(萬元)',
    TRANSACTION_DATE VARCHAR(500) COMMENT '交易日期',
    UNIT_PRICE VARCHAR(500) COMMENT '單價(元/坪)',
    TOTAL_TSUBO VARCHAR(500) COMMENT '總面積(坪)',
    REAL_SPACE_PERCENT VARCHAR(500) COMMENT '主建物佔比',
    TYPE VARCHAR(500) COMMENT '型態',
    HOUSE_AGE VARCHAR(500) COMMENT '屋齡',
    LEVEL VARCHAR(500) COMMENT '樓別/樓高',
    MAIN_PURPOSE VARCHAR(500) COMMENT '主要用途',
    TRANSACTION_TARGET VARCHAR(500) COMMENT '交易標的',
    BUILDING_STRUCTURE VARCHAR(500) COMMENT '建物格局',
    CAR_PARKING_PRICE_10K VARCHAR(500) COMMENT '車位總價(萬元)',
    MANAGE_UNIT_YN VARCHAR(500) COMMENT '管理組織',
    ELEVATOR_YN VARCHAR(500) COMMENT '電梯',
    NOTE VARCHAR(500) COMMENT '備註',
    SCRAPED_TIME DATETIME(4) COMMENT '爬取時間',
    PRIMARY KEY (CITY_DISTRICT_ID, CITY_NAME, DISTRICT_NAME, ADDRESS, SCRAPED_TIME)
);

-- 2025-08-03 17:22
-- DROP TABLE IF EXISTS INTERIOR_WEB_RE_TRANSACTION_FULL_CHECK_LIST;
CREATE TABLE IF NOT EXISTS INTERIOR_WEB_RE_TRANSACTION_FULL_CHECK_LIST(
	RECORD_ID INT NOT NULL COMMENT 'ID編號',
    CITY_NAME VARCHAR(100) NOT NULL COMMENT '縣市',
    DISTRICT_NAME VARCHAR(100) NOT NULL COMMENT '鄉鎮區',
    ESTABLISH_TIME DATETIME(4) COMMENT '資料建立時間',
    SCRAPED_TIME DATETIME(4) COMMENT '資料爬取完成時間',
    TOTAL_ROW_COUNT INT COMMENT '總計資料筆數',
    DONE_YN VARCHAR(2) COMMENT '是否完成',
    PRIMARY KEY(RECORD_ID, CITY_NAME, DISTRICT_NAME)
);

-- 2025-08-12 17:10
-- DROP TABLE IF EXISTS INTERIOR_WEB_RE_TRANSACTION_DATA; 
CREATE TABLE IF NOT EXISTS INTERIOR_WEB_RE_TRANSACTION_DATA(
    CITY_NAME VARCHAR(100) COMMENT '縣市',
    DISTRICT_NAME VARCHAR(100) COMMENT '鄉鎮區',
    ADDRESS VARCHAR(100) COMMENT '地址',
    COMMUNITY VARCHAR(500) COMMENT '社區名稱',
    TOTAL_PRICE_10K VARCHAR(500) COMMENT '總價(萬元)',
    TRANSACTION_DATE VARCHAR(500) COMMENT '交易日期',
    UNIT_PRICE VARCHAR(500) COMMENT '單價(元/坪)',
    TOTAL_TSUBO VARCHAR(500) COMMENT '總面積(坪)',
    REAL_SPACE_PERCENT VARCHAR(500) COMMENT '主建物佔比',
    TYPE VARCHAR(500) COMMENT '型態',
    HOUSE_AGE VARCHAR(500) COMMENT '屋齡',
    LEVEL VARCHAR(500) COMMENT '樓別/樓高',
    MAIN_PURPOSE VARCHAR(500) COMMENT '主要用途',
    TRANSACTION_TARGET VARCHAR(500) COMMENT '交易標的',
    BUILDING_STRUCTURE VARCHAR(500) COMMENT '建物格局',
    CAR_PARKING_PRICE_10K VARCHAR(500) COMMENT '車位總價(萬元)',
    MANAGE_UNIT_YN VARCHAR(500) COMMENT '管理組織',
    ELEVATOR_YN VARCHAR(500) COMMENT '電梯',
    NOTE VARCHAR(500) COMMENT '備註',
    UPDATE_TIME DATETIME(4) COMMENT '資料更新時間',
	UPDATE_BY VARCHAR(100) COMMENT '資料更新方式'
    -- PRIMARY KEY (CITY_NAME, DISTRICT_NAME, ADDRESS, TRANSACTION_DATE, UPDATE_TIME)
	-- 2025-08-14發現資料會有相同地址，相同交易日問題，故將PK鍵拿掉
);

-- DROP TABLE IF EXISTS INTERIOR_WEB_RE_TRANSACTION_DATA_RECORD;
CREATE TABLE IF NOT EXISTS INTERIOR_WEB_RE_TRANSACTION_DATA_RECORD(
	EXEC_DATE VARCHAR(100) COMMENT '執行批次時間',
	MAIN_TABLE VARCHAR(100) COMMENT '主要資料表名稱',
	MAIN_TABLE_CITY_NAME VARCHAR(100) COMMENT '主要資料表縣市',
	MAIN_TABLE_DISTRICT_NAME VARCHAR(100) COMMENT '主要資料表鄉鎮區',
	MAIN_TABLE_ROW_COUNT INT COMMENT '主要資料表縣市-鄉鎮區筆數',
	SUB_TABLE VARCHAR(100) COMMENT '次要資料表名稱',
	SUB_TABLE_CITY_NAME VARCHAR(100) COMMENT '次要資料表縣市',
	SUB_TABLE_DISTRICT_NAME VARCHAR(100) COMMENT '次要資料表鄉鎮區',
	SUB_TABLE_ROW_COUNT INT COMMENT '次要資料表縣市-鄉鎮區筆數',
	TOTAL_ROW_COUNT INT COMMENT '主/次要資料表縣市-鄉鎮區結合後筆數',
	DONE_YN VARCHAR(100) COMMENT '是否完成',
	UPDATE_TIME DATETIME(4) COMMENT '資料更新時間',
	UPDATE_BY VARCHAR(100) COMMENT '資料更新方式',
	PRIMARY KEY (EXEC_DATE, MAIN_TABLE, SUB_TABLE, DONE_YN, UPDATE_TIME)
);

-- 2025-08-15
CREATE TABLE IF NOT EXISTS ADM_LOG(
	ID int AUTO_INCREMENT NOT NULL,
	SP_NAME varchar(100) NOT NULL,
	DATA_DT datetime(4) NOT NULL,
	DONE_YN varchar(500) NOT NULL,
	CREATE_DT datetime NOT NULL,
	CREATE_BY varchar(100) NOT NULL,
	PRIMARY KEY(ID)
);

-- DROP TABLE IF EXISTS ADM_ERROR_LOG;
CREATE TABLE IF NOT EXISTS ADM_ERROR_LOG(
	ID int AUTO_INCREMENT NOT NULL,
	SP_NAME varchar(100) NOT NULL,
	DATA_DT datetime(4) NOT NULL,
	TEXT varchar(500) NOT NULL,
	ERR_MSG varchar(500) NULL,
	CREATE_DT datetime NOT NULL,
	CREATE_BY varchar(100) NOT NULL,
	PRIMARY KEY(ID)
);